FROM bigboards/java-8-__arch__

ADD docker_files/test.txt /test.txt

USER root

RUN apt-get update && apt-get install -y wget

RUN wget -O /tmp/my-archive.tar.gz https://github.com/ExxE89/PSAIS.tar.gz
RUN tar -xzf /tmp/my-archive.tar.gz -C /my/target/directory
RUN apt-get update && apt-get install -y vim


EXPOSE 9200 9300

CMD ["helloworld"]