classifier: naive_bayes

database:
  host: 141.7.63.160:9200

log_level: DEBUG

aggregation:
  time_interval_minutes: 10

spark_master: spark://141.7.63.156:7077

search_filter:
  range:
    date:
      gte: now-15m
