classifier: polarity

database:
  host: 127.0.0.1:9200

log_level: DEBUG

aggregation:
  time_interval_minutes: 10

spark_master: spark://141.7.63.156:7077

search_filter:
  range:
    date: # Format: https://www.elastic.co/guide/en/elasticsearch/guide/current/_ranges.html#_ranges_on_dates
      gte: 2015
      lt: 2018
